language: c

os:
  - linux
  - osx

before_script:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

sudo: required

dist: trusty 

compiler:
  - gcc

install: 
  - ./.install-$TRAVIS_OS_NAME-deps.sh

addons:
  apt:
    # Travis whitelist of packages.
    # https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-trusty
    packages:
      - cmake
      - gcc
      - gfortran

env:
  - PETSC_WITH_HDF5=1
  - PETSC_WITH_HDF5=0

script: 
  - ./pflotran-build-test.sh

notifications:
  email:
    on_success: always
    on_failure: always
